site_name: DungeonsHub
site_url: https://dungeonss.vercel.app
theme:
  name: material
  custom_dir: .overrides
  logo: images/icon.webp
  favicon: images/icon.webp
  palette:
    primary: deep purple
    accent: amber
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - content.code.copy
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js

copyright: Made with ❤️ by Arno

extra:
  generator: true

nav:
  - Home: index.md
  - Agenciak's Guides:
    - agenciak/index.md
    - Melee Guide: agenciak/agenciak-melee-guide.md
    - Rolling Guide: agenciak/agenciak-rolling-guide.md
    - Enhancements Guide: agenciak/agenciak-enhancements.md
    - Glossary: agenciak/agenciak-glossary.md
  - BusterCat's Guides:
    - bustercat/index.md
    - Tank Builds: bustercat/bustercat-tank-builds.md
    - Move-Attack Guide: bustercat/bustercat-move-attack-guide.md
    - Armor Swapping Guide: bustercat/bustercat-armor-swapping-guide.md
    - Tierlist: bustercat/bustercat-tierlist.md
    - Tankiest Rolling Builds Guide: bustercat/bustercat-tankiest-rolling-builds-guide.md
  - GrimReaper's Guides:
    - grimreaper/index.md
    - Halloween Stings Build: grimreaper/grimreaper-halloween-stings-build.md
  - Pancake's Guides:
    - pancake/index.md
    - Spear Guide Part I: pancake/pancake-spear-guide.md
    - Spear Guide Part II: pancake/pancake-spear-guide-part-2.md
    - Best Starless Melee Builds: pancake/pancake-best-starless-melee-builds.md
    - Best Starless Enchants: pancake/pancake-best-starless-enchants.md
    - Harp God Rolls: pancake/pancake-harp-god-rolls.md
    - Why Illagers Bane Bad: pancake/pancake-why-illagers-bane-bad.md
    - Katana God Rolls: pancake/pancake-katana-god-rolls.md
    - Sawblade Best Enchants: pancake/pancake-sawblade-best-enchants.md
    - Melee Build Armor Guide: pancake/pancake-melee-build-armor-guide.md
    - Fighters Bindings God Rolls: pancake/pancake-fighters-bindings-god-rolls.md
    - Mob Health Chart: pancake/pancake-mob-health-chart.md
    - Crossbow Guide: pancake/pancake-crossbow-guide.md
    - Frostbite Guide: pancake/pancake-frostbite-guide.md
    - Rapier Guide: pancake/pancake-rapier-guide.md
    - DPS Data: pancake/pancake-dps-data.md
    - Pain Cycle Guide: pancake/pancake-pain-cycle-guide.md
    - Hits Per Second Chart: pancake/pancake-hits-per-second-chart.md
  - Shin's Guides:
    - shins/index.md
    - Why Protection Bad: shins/shin-why-protection-bad.md
    - In Depth Build Guide: shins/shin-in-depth-build-guide.md
    - Damage Reduction Stacking Guide: shins/shin-damage-reduction-stacking-guide.md
    - Leeching Vs Radiance Ratio: shins/shin-leeching-vs-radiance-ratio.md
    - DPS Tier List: shins/shin-dps-tier-list.md
    - Ranged Guide: shins/shin-ranged-guide.md
    - Pain Cycle Impact Guide: shins/shin-pain-cycle-impact-guide.md
    - Void Strike Impact Guide: shins/shin-void-strike-impact-guide.md
    - Thundering Guide: shins/shin-thundering-guide.md
    - Weapons Guide: shins/shin-weapons-guide.md
    - Scythe Guide: shins/shin-scythe-guide.md
    - Moon Daggers Guide: shins/shin-moon-daggers-guide.md
    - The Beginning And The End Guide: shins/shin-the-beginning-and-the-end-guide.md
    - Battlestaff Of Terror Guide: shins/shin-battlestaff-of-terror-guide.md
    - Encrusted Anchor Guide: shins/shin-encrusted-anchor-guide.md
    - Nameless Blade Guide: shins/shin-nameless-blade-guide.md
    - Mechanized Sawblade Guide: shins/shin-mechanized-sawblade-guide.md
    - Rapier Guide: shins/shin-rapier-guide.md
    - Backstabber Guide: shins/shin-backstabber-guide.md
    - Double Axe Guide: shins/shin-double-axe-guide.md
  - Reddit Guides:
    - reddit/index.md
    - Ancient Hunts: reddit/reddit-ancient-hunts.md
    - Soul Artifacts Guide: reddit/reddit-soul-artifacts-guide.md
    - Runes Guide: reddit/reddit-runes-guide.md
    - Artifact Drop Guide: reddit/reddit-artifact-drop-guide.md
    - How To Find Best Ranged: reddit/reddit-how-to-find-best-ranged.md
  - Other Sources:
    - other/index.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
